-- 1. Setup Custom Enum Types
CREATE TYPE admin_status_type AS ENUM ('active', 'inactive');
CREATE TYPE kabataan_status_type AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE event_status_type AS ENUM ('draft', 'scheduled', 'ongoing', 'completed', 'cancelled');
CREATE TYPE attendance_status_type AS ENUM ('registered', 'attended', 'absent');

-- 2. Core Identity Tables (Supabase Auth Integration)
CREATE TABLE admins (
    admin_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    status admin_status_type DEFAULT 'active',
    contact_number TEXT NULL, 
    position TEXT NULL, 
    barangay TEXT NULL, 
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE kabataan_profiles (
    profile_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    status kabataan_status_type DEFAULT 'pending',
    age INT NULL,
    gender VARCHAR(20) NULL,
    purok VARCHAR(50) NULL,
    address_line VARCHAR(255) NULL,
    scholar_status VARCHAR(30) NULL,
    educational_status VARCHAR(100) NULL,
    profile_image TEXT NULL, 
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Source of Truth: Annual Budget
CREATE TABLE annual_budgets (
    budget_year_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year INT UNIQUE NOT NULL,
    total_allocation DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    remaining_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Survey Management (Create Survey Panel)
CREATE TABLE surveys (
    survey_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_year_id INT REFERENCES annual_budgets(budget_year_id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    question_text TEXT NOT NULL,
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE survey_activities (
    activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id INT REFERENCES surveys(survey_id) ON DELETE CASCADE,
    category_name VARCHAR(100) NOT NULL,
    activity_name VARCHAR(100) NOT NULL
);

CREATE TABLE survey_votes (
    vote_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id INT REFERENCES survey_activities(activity_id) ON DELETE CASCADE,
    user_id UUID REFERENCES kabataan_profiles(profile_id) ON DELETE CASCADE,
    voted_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_activity_vote UNIQUE (activity_id, user_id)
);

-- 5. Possible Activities & The Calendar Scheduling System
CREATE TABLE events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_year_id INT REFERENCES annual_budgets(budget_year_id) ON DELETE CASCADE,
    event_name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    allocated_budget DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status event_status_type DEFAULT 'draft',
    event_date DATE NULL,
    event_time VARCHAR(20) NULL,
    location VARCHAR(150) NULL,
    expected_attendees INT DEFAULT 0,
    cover_image TEXT,
    description TEXT,
    created_by UUID REFERENCES admins(admin_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Financial & Operational Tracking
CREATE TABLE event_expenses (
    expense_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT REFERENCES events(event_id) ON DELETE CASCADE,
    expense_type VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    description TEXT,
    expense_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE event_registrations (
    registration_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT REFERENCES events(event_id) ON DELETE CASCADE,
    user_id UUID REFERENCES kabataan_profiles(profile_id) ON DELETE CASCADE,
    registration_date TIMESTAMPTZ DEFAULT NOW(),
    attendance_status attendance_status_type DEFAULT 'registered',
    CONSTRAINT unique_event_registration UNIQUE (event_id, user_id)
);

CREATE TABLE post_event_feedback (
    feedback_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT REFERENCES events(event_id) ON DELETE CASCADE,
    user_id UUID REFERENCES kabataan_profiles(profile_id) ON DELETE CASCADE,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    comments TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE kabataan_suggestions (
    suggestion_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES kabataan_profiles(profile_id) ON DELETE CASCADE,
    message TEXT NOT NULL CHECK (length(trim(message)) > 0),
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);
