begin;

create or replace function public.is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where admin_id = auth.uid()
      and status = 'active'
  );
$$;

revoke all on function public.is_active_admin() from public, anon;
grant execute on function public.is_active_admin() to authenticated;

create table if not exists public.announcements (
  announcement_id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) > 0),
  content text not null check (length(trim(content)) > 0),
  category text,
  priority integer not null default 0 check (priority >= 0),
  is_published boolean not null default false,
  publish_at timestamptz not null default now(),
  expires_at timestamptz,
  image_path text,
  created_by uuid not null references public.admins(admin_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or expires_at > publish_at)
);

alter table public.announcements enable row level security;

create index if not exists announcements_visible_idx
on public.announcements (is_published, publish_at, expires_at, priority desc, created_at desc);

create or replace function public.set_announcement_audit_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Only active admins can manage announcements';
  end if;

  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.created_at := coalesce(new.created_at, now());
    new.updated_at := now();
  elsif tg_op = 'UPDATE' then
    new.created_by := old.created_by;
    new.created_at := old.created_at;
    new.updated_at := now();
  end if;

  return new;
end;
$$;

revoke all on function public.set_announcement_audit_fields() from public, anon;

drop trigger if exists set_announcement_audit_fields on public.announcements;
create trigger set_announcement_audit_fields
before insert or update on public.announcements
for each row execute function public.set_announcement_audit_fields();

drop policy if exists "Youth can read visible announcements" on public.announcements;
drop policy if exists "Active admins can read all announcements" on public.announcements;
drop policy if exists "Active admins can insert announcements" on public.announcements;
drop policy if exists "Active admins can update announcements" on public.announcements;
drop policy if exists "Active admins can delete announcements" on public.announcements;

create policy "Youth can read visible announcements"
on public.announcements
for select
to authenticated
using (
  is_published = true
  and publish_at <= now()
  and (expires_at is null or expires_at > now())
);

create policy "Active admins can read all announcements"
on public.announcements
for select
to authenticated
using (public.is_active_admin());

create policy "Active admins can insert announcements"
on public.announcements
for insert
to authenticated
with check (public.is_active_admin());

create policy "Active admins can update announcements"
on public.announcements
for update
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create policy "Active admins can delete announcements"
on public.announcements
for delete
to authenticated
using (public.is_active_admin());

alter table public.survey_questions
add column if not exists reporting_key text
check (reporting_key is null or reporting_key in ('preferred_activity_type', 'suggested_event'));

create index if not exists survey_questions_reporting_key_idx on public.survey_questions(reporting_key);
create index if not exists survey_answers_question_id_idx on public.survey_answers(question_id);
create index if not exists survey_responses_user_id_idx on public.survey_responses(user_id);
create index if not exists event_registrations_user_id_idx on public.event_registrations(user_id);
create index if not exists event_registrations_event_id_idx on public.event_registrations(event_id);

create or replace function public.get_admin_survey_response_details(p_survey_id integer default null, p_search text default null)
returns table (
  response_id integer,
  survey_id integer,
  survey_title text,
  profile_id uuid,
  fullname text,
  email text,
  purok text,
  gender text,
  submitted_at timestamptz,
  answers jsonb
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Only active admins can view identified survey responses';
  end if;

  return query
  select
    sr.response_id,
    sr.survey_id,
    s.title::text as survey_title,
    kp.profile_id,
    kp.fullname::text,
    kp.email::text,
    kp.purok::text,
    kp.gender::text,
    sr.submitted_at,
    coalesce(jsonb_agg(jsonb_build_object(
      'question_id', sq.question_id,
      'question_text', sq.question_text,
      'question_type', sq.question_type,
      'answer_text', sa.answer_text,
      'selected_options', coalesce(opts.options, '[]'::jsonb)
    ) order by sq.sort_order, sq.question_id) filter (where sa.answer_id is not null), '[]'::jsonb) as answers
  from public.survey_responses sr
  join public.surveys s on s.survey_id = sr.survey_id
  join public.kabataan_profiles kp on kp.profile_id = sr.user_id
  left join public.survey_answers sa on sa.response_id = sr.response_id
  left join public.survey_questions sq on sq.question_id = sa.question_id
  left join lateral (
    select jsonb_agg(jsonb_build_object('option_id', so.option_id, 'option_text', so.option_text) order by so.sort_order, so.option_id) as options
    from public.survey_answer_options sao
    join public.survey_options so on so.option_id = sao.option_id
    where sao.answer_id = sa.answer_id
  ) opts on true
  where (p_survey_id is null or sr.survey_id = p_survey_id)
    and (p_search is null or trim(p_search) = '' or kp.fullname ilike '%' || trim(p_search) || '%' or kp.email ilike '%' || trim(p_search) || '%')
  group by sr.response_id, sr.survey_id, s.title, kp.profile_id, kp.fullname, kp.email, kp.purok, kp.gender, sr.submitted_at
  order by sr.submitted_at desc;
end;
$$;

revoke all on function public.get_admin_survey_response_details(integer, text) from public, anon;
grant execute on function public.get_admin_survey_response_details(integer, text) to authenticated;

create or replace function public.get_my_survey_responses()
returns table (response_id integer, survey_id integer, survey_title text, submitted_at timestamptz, answers jsonb)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  return query
  select sr.response_id, sr.survey_id, s.title::text, sr.submitted_at,
    coalesce(jsonb_agg(jsonb_build_object(
      'question_id', sq.question_id,
      'question_text', sq.question_text,
      'question_type', sq.question_type,
      'answer_text', sa.answer_text,
      'selected_options', coalesce(opts.options, '[]'::jsonb)
    ) order by sq.sort_order, sq.question_id) filter (where sa.answer_id is not null), '[]'::jsonb) as answers
  from public.survey_responses sr
  join public.surveys s on s.survey_id = sr.survey_id
  left join public.survey_answers sa on sa.response_id = sr.response_id
  left join public.survey_questions sq on sq.question_id = sa.question_id
  left join lateral (
    select jsonb_agg(jsonb_build_object('option_id', so.option_id, 'option_text', so.option_text) order by so.sort_order, so.option_id) as options
    from public.survey_answer_options sao
    join public.survey_options so on so.option_id = sao.option_id
    where sao.answer_id = sa.answer_id
  ) opts on true
  where sr.user_id = auth.uid()
  group by sr.response_id, sr.survey_id, s.title, sr.submitted_at
  order by sr.submitted_at desc;
end;
$$;

revoke all on function public.get_my_survey_responses() from public, anon;
grant execute on function public.get_my_survey_responses() to authenticated;

create or replace view public.survey_preferred_activity_types
with (security_invoker = true)
as
with relevant_answers as (
  select distinct sr.response_id, sr.user_id, s.survey_id, s.title as source_survey, sq.question_id, so.option_id, so.option_text as activity_type
  from public.survey_responses sr
  join public.surveys s on s.survey_id = sr.survey_id
  join public.survey_answers sa on sa.response_id = sr.response_id
  join public.survey_questions sq on sq.question_id = sa.question_id
  join public.survey_answer_options sao on sao.answer_id = sa.answer_id
  join public.survey_options so on so.option_id = sao.option_id
  where s.status in ('published', 'closed')
    and sq.question_type in ('single_choice', 'multiple_choice')
    and (sq.reporting_key = 'preferred_activity_type' or lower(sq.question_text) like any (array['%preferred activity%', '%activity type%', '%program type%', '%interest%']))
),
option_counts as (
  select activity_type, count(*)::int as selection_count, count(distinct user_id)::int as respondent_count, array_agg(distinct source_survey order by source_survey) as source_surveys
  from relevant_answers
  group by activity_type
),
totals as (
  select count(*)::numeric as total_selections, count(distinct user_id)::numeric as total_respondents
  from relevant_answers
)
select
  row_number() over (order by respondent_count desc, selection_count desc, activity_type) as rank,
  activity_type,
  respondent_count,
  total_respondents::int,
  case when total_respondents > 0 then round((respondent_count::numeric / total_respondents) * 100, 2) else 0 end as respondent_percentage,
  selection_count,
  total_selections::int,
  case when total_selections > 0 then round((selection_count::numeric / total_selections) * 100, 2) else 0 end as selection_share_percentage,
  source_surveys
from option_counts, totals;

revoke all on public.survey_preferred_activity_types from public, anon, authenticated;

create or replace view public.survey_top_suggested_events
with (security_invoker = true)
as
with raw_suggestions as (
  select distinct sr.response_id, sr.user_id, s.title as source_survey, lower(trim(so.option_text)) as normalized_name, trim(so.option_text) as display_name, null::text as category
  from public.survey_responses sr
  join public.surveys s on s.survey_id = sr.survey_id
  join public.survey_answers sa on sa.response_id = sr.response_id
  join public.survey_questions sq on sq.question_id = sa.question_id
  join public.survey_answer_options sao on sao.answer_id = sa.answer_id
  join public.survey_options so on so.option_id = sao.option_id
  where s.status in ('published', 'closed')
    and nullif(trim(so.option_text), '') is not null
    and (sq.reporting_key = 'suggested_event' or lower(sq.question_text) like any (array['%suggested event%', '%event suggestion%', '%activity suggestion%']))
  union all
  select distinct sr.response_id, sr.user_id, s.title as source_survey, lower(trim(sa.answer_text)) as normalized_name, trim(sa.answer_text) as display_name, null::text as category
  from public.survey_responses sr
  join public.surveys s on s.survey_id = sr.survey_id
  join public.survey_answers sa on sa.response_id = sr.response_id
  join public.survey_questions sq on sq.question_id = sa.question_id
  where s.status in ('published', 'closed')
    and sq.question_type in ('short_text', 'long_text')
    and nullif(trim(sa.answer_text), '') is not null
    and (sq.reporting_key = 'suggested_event' or lower(sq.question_text) like any (array['%suggested event%', '%event suggestion%', '%activity suggestion%']))
),
deduped_support as (
  select distinct user_id, normalized_name
  from raw_suggestions
  where normalized_name <> ''
),
grouped as (
  select
    r.normalized_name,
    initcap(min(r.display_name)) as suggested_event_name,
    coalesce(max(r.category), 'Uncategorized') as category,
    count(*)::int as submission_count,
    count(distinct r.user_id)::int as respondent_count,
    array_agg(distinct r.source_survey order by r.source_survey) as source_surveys
  from raw_suggestions r
  where r.normalized_name <> ''
  group by r.normalized_name
),
total as (
  select count(*)::numeric as total_distinct_support
  from deduped_support
),
planned as (
  select event_id, lower(trim(event_name)) as normalized_name
  from public.events
  where status in ('scheduled', 'ongoing')
)
select
  row_number() over (order by g.respondent_count desc, g.submission_count desc, g.suggested_event_name) as rank,
  g.suggested_event_name,
  g.category,
  g.respondent_count,
  g.submission_count,
  case when total.total_distinct_support > 0 then round((g.respondent_count::numeric / total.total_distinct_support) * 100, 2) else 0 end as respondent_support_percentage,
  g.source_surveys,
  (p.event_id is not null) as is_already_planned,
  p.event_id as matching_event_id
from grouped g
cross join total
left join planned p on p.normalized_name = g.normalized_name;

revoke all on public.survey_top_suggested_events from public, anon, authenticated;

create or replace function public.get_admin_preferred_activity_types()
returns setof public.survey_preferred_activity_types
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Only active admins can view survey analytics';
  end if;

  return query select * from public.survey_preferred_activity_types;
end;
$$;

create or replace function public.get_admin_top_suggested_events()
returns setof public.survey_top_suggested_events
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Only active admins can view survey analytics';
  end if;

  return query select * from public.survey_top_suggested_events;
end;
$$;

revoke all on function public.get_admin_preferred_activity_types() from public, anon;
revoke all on function public.get_admin_top_suggested_events() from public, anon;
grant execute on function public.get_admin_preferred_activity_types() to authenticated;
grant execute on function public.get_admin_top_suggested_events() to authenticated;

drop policy if exists "Users can view registrations" on public.event_registrations;
drop policy if exists "Users can register themselves" on public.event_registrations;
drop policy if exists "Users can cancel registrations" on public.event_registrations;
drop policy if exists "Youth can read own registrations" on public.event_registrations;
drop policy if exists "Active admins can read registrations" on public.event_registrations;
drop policy if exists "Block direct registration inserts" on public.event_registrations;
drop policy if exists "Block direct registration updates" on public.event_registrations;
drop policy if exists "Block direct registration deletes" on public.event_registrations;

create policy "Youth can read own registrations"
on public.event_registrations
for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Active admins can read registrations"
on public.event_registrations
for select
to authenticated
using (public.is_active_admin());

create or replace function public.register_youth_for_event(p_event_id int)
returns table (registration_id integer, event_id integer, user_id uuid, registration_date timestamptz, attendance_status public.attendance_status_type)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.events;
  v_slot_count int;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (select 1 from public.kabataan_profiles where profile_id = auth.uid() and status = 'approved') then
    raise exception 'Approved Youth profile required';
  end if;

  select * into v_event from public.events where events.event_id = p_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if v_event.status <> 'scheduled' then raise exception 'Event is not open for registration'; end if;
  if v_event.event_date is null or v_event.event_date < current_date then raise exception 'Event registration is closed'; end if;

  select count(*) into v_slot_count
  from public.event_registrations er
  where er.event_id = p_event_id and er.attendance_status in ('registered', 'attended');

  if coalesce(v_event.expected_attendees, 0) > 0 and v_slot_count >= v_event.expected_attendees then
    raise exception 'Event is already full';
  end if;

  return query
  insert into public.event_registrations (event_id, user_id, attendance_status)
  values (p_event_id, auth.uid(), 'registered')
  returning event_registrations.registration_id, event_registrations.event_id, event_registrations.user_id, event_registrations.registration_date, event_registrations.attendance_status;
exception
  when unique_violation then
    raise exception 'Already registered for this event';
end;
$$;

create or replace function public.cancel_youth_event_registration(p_event_id int)
returns table (cancelled boolean, registration_id integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.events;
  v_registration_id integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not exists (select 1 from public.kabataan_profiles where profile_id = auth.uid() and status = 'approved') then
    raise exception 'Approved Youth profile required';
  end if;

  select * into v_event from public.events where events.event_id = p_event_id;
  if not found then raise exception 'Event not found'; end if;
  if v_event.status in ('completed', 'cancelled') then raise exception 'Registration can no longer be cancelled'; end if;
  if v_event.event_date is not null and v_event.event_date < current_date then raise exception 'Past event registration cannot be cancelled'; end if;

  delete from public.event_registrations er
  where er.event_id = p_event_id and er.user_id = auth.uid()
  returning er.registration_id into v_registration_id;

  if v_registration_id is null then raise exception 'Registration not found'; end if;
  return query select true, v_registration_id;
end;
$$;

revoke all on function public.register_youth_for_event(int) from public, anon;
revoke all on function public.cancel_youth_event_registration(int) from public, anon;
grant execute on function public.register_youth_for_event(int) to authenticated;
grant execute on function public.cancel_youth_event_registration(int) to authenticated;

commit;
