create table if not exists public.event_categories (
  category_id bigint generated by default as identity primary key,
  name text not null,
  description text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint event_categories_name_not_blank check (length(trim(name)) > 0),
  constraint event_categories_name_unique unique (name)
);

alter table public.event_categories enable row level security;

drop policy if exists "Authenticated users can view active event categories" on public.event_categories;
create policy "Authenticated users can view active event categories"
on public.event_categories
for select
to authenticated
using (is_active or public.is_active_admin());

drop policy if exists "Active admins can insert event categories" on public.event_categories;
create policy "Active admins can insert event categories"
on public.event_categories
for insert
to authenticated
with check (public.is_active_admin());

drop policy if exists "Active admins can update event categories" on public.event_categories;
create policy "Active admins can update event categories"
on public.event_categories
for update
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

drop policy if exists "Active admins can delete event categories" on public.event_categories;
create policy "Active admins can delete event categories"
on public.event_categories
for delete
to authenticated
using (public.is_active_admin());

grant select on public.event_categories to authenticated;
grant insert, update, delete on public.event_categories to authenticated;
grant usage, select on sequence public.event_categories_category_id_seq to authenticated;

create or replace function public.set_event_categories_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_event_categories_updated_at on public.event_categories;
create trigger set_event_categories_updated_at
before update on public.event_categories
for each row
execute function public.set_event_categories_updated_at();

insert into public.event_categories (name, sort_order)
select seed.name, seed.sort_order
from (
  values
    ('Sports', 10),
    ('Training', 20),
    ('Community Service', 30),
    ('Health & Wellness', 40),
    ('Cultural', 50)
) as seed(name, sort_order)
where not exists (
  select 1
  from public.event_categories existing
  where lower(trim(existing.name)) = lower(trim(seed.name))
);

insert into public.event_categories (name, sort_order)
select distinct trim(e.category), 100
from public.events e
where nullif(trim(e.category), '') is not null
  and not exists (
    select 1
    from public.event_categories existing
    where lower(trim(existing.name)) = lower(trim(e.category))
  );

create or replace function public.update_admin_annual_budget(
  p_budget_year_id integer,
  p_total_allocation numeric
)
returns public.annual_budgets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_budget public.annual_budgets;
  v_completed_spending numeric := 0;
begin
  if not public.is_active_admin() then
    raise exception 'Only active admins can update annual budgets.';
  end if;

  if p_budget_year_id is null then
    raise exception 'Budget year is required.';
  end if;

  if p_total_allocation is null or p_total_allocation < 0 then
    raise exception 'Annual budget must be zero or greater.';
  end if;

  select coalesce(sum(amount), 0)
  into v_completed_spending
  from public.financial_transactions
  where budget_year_id = p_budget_year_id
    and status = 'completed'
    and transaction_type in ('expense', 'disbursement', 'reimbursement');

  update public.annual_budgets
  set
    total_allocation = p_total_allocation,
    remaining_balance = p_total_allocation - v_completed_spending
  where budget_year_id = p_budget_year_id
  returning * into v_budget;

  if v_budget.budget_year_id is null then
    raise exception 'Budget year was not found.';
  end if;

  return v_budget;
end;
$$;

revoke all on function public.update_admin_annual_budget(integer, numeric) from public, anon;
grant execute on function public.update_admin_annual_budget(integer, numeric) to authenticated;
