-- Admin notifications, completed event performance, and dashboard decision-support support.
-- Applied to Supabase as migration: admin_notifications_performance_dashboard_support.

create table if not exists public.admin_notifications (
  notification_id bigint generated by default as identity primary key,
  notification_key text unique,
  type text not null,
  title text not null,
  message text not null,
  related_user_id uuid null references public.kabataan_profiles(profile_id) on delete set null,
  related_event_id integer null references public.events(event_id) on delete set null,
  related_survey_id integer null references public.surveys(survey_id) on delete set null,
  related_feedback_id integer null references public.post_event_feedback(feedback_id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint admin_notifications_type_check check (
    type in (
      'youth_created',
      'event_registration_created',
      'event_registration_cancelled',
      'survey_response_submitted',
      'event_feedback_authenticated',
      'event_feedback_guest',
      'youth_suggestion_submitted'
    )
  )
);

alter table public.admin_notifications enable row level security;

create index if not exists admin_notifications_created_at_idx on public.admin_notifications(created_at desc);
create index if not exists admin_notifications_unread_idx on public.admin_notifications(is_read, created_at desc) where is_read = false;
create index if not exists admin_notifications_related_event_idx on public.admin_notifications(related_event_id) where related_event_id is not null;

drop policy if exists "Active admins can read admin notifications" on public.admin_notifications;
create policy "Active admins can read admin notifications"
on public.admin_notifications
for select
to authenticated
using (public.is_active_admin());

drop policy if exists "Active admins can update notification read state" on public.admin_notifications;
create policy "Active admins can update notification read state"
on public.admin_notifications
for update
to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

create or replace function public.create_admin_notification(
  p_notification_key text,
  p_type text,
  p_title text,
  p_message text,
  p_related_user_id uuid default null,
  p_related_event_id integer default null,
  p_related_survey_id integer default null,
  p_related_feedback_id integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admin_notifications (
    notification_key,
    type,
    title,
    message,
    related_user_id,
    related_event_id,
    related_survey_id,
    related_feedback_id,
    metadata
  )
  values (
    p_notification_key,
    p_type,
    p_title,
    p_message,
    p_related_user_id,
    p_related_event_id,
    p_related_survey_id,
    p_related_feedback_id,
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (notification_key) do nothing;
end;
$$;

revoke all on function public.create_admin_notification(text, text, text, text, uuid, integer, integer, integer, jsonb) from public, anon, authenticated;

-- The full trigger/RPC definitions are maintained in the applied Supabase migration.
-- This local mirror records the schema object names and should be kept in sync with remote.
